import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
      <h1 className="text-2xl font-extrabold text-gray-800 mb-4 text-center leading-tight">
  Where hackers and builders believe in you!
</h1>

<h1 className="text-gray-600 font-bold text-xl mb-4 text-center leading-tight">
  Connect with your favourite side hustlers and fund your favourite project.
</h1>


        <div className="flex flex-col md:flex-row justify-between items-center mt-10">
          <div className="w-full md:w-1/2 bg-gray-100 rounded-md p-6 shadow-lg hover:shadow-xl cursor-pointer">
            <h2 className="text-xl font-bold text-gray-700 mb-4">
              Explore other creations
            </h2>
            <p className="text-gray-600 mb-4">
              Discover new products and ideas from other creators.
            </p>
            <button className="bg-red-500 text-white font-bold py-2 px-4 rounded-full shadow-lg hover:shadow-xl">
              Explore
            </button>
          </div>
          <div className="w-full md:w-1/2 bg-gray-100 rounded-md p-6 shadow-lg hover:shadow-xl cursor-pointer mt-4 md:mt-0">
            <h2 className="text-xl font-bold text-gray-700 mb-4">
              Pitch your own product
            </h2>
            <p className="text-gray-600 mb-4">
              Share your ideas and get feedback from the community.
            </p>
            <button className="bg-red-500 text-white font-bold py-2 px-4 rounded-full shadow-lg hover:shadow-xl">
              Pitch
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
